### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by srvoets** [dennyreiter/GoalHorn#1]
Hey bud, this isnt an issue so much as a question as this is my first time using Node Red

Is it pulling team ID from the sensors.yaml?  Or does team ID need to be set on the node?

I think Im doing this correctly, which would setting entities for the following nodes:

-Speaker
-Light
-Location of goal horns folder

Im assuming it chooses the correct horn based on the team ID that is set?  Just wanna make sure I dont have to set it in Node Red

**Comment by dennyreiter** [comment]
The team ID is sent in the event trigger.  A good way to help understand it would be to put a debug node after the NHL events node (first one) and set the output to "complete msg object." Then when it triggers you can examine everything that is sent.

I just realized I haven't touched this in forever.  My current flow is pretty different.  I'll get it updated.

**Comment by dennyreiter** [comment]
I updated everything to show what I use now.  I think it's a bit more readable, also.
