### ISSUE TITLE
Team horn sound

### ISSUE THREAD

**Issue by nutsofamily** [dennyreiter/GoalHorn#3]
Does the flow sound all teams playing? Is there a way to only setup your fav teams?
Ill try it out tonight as I just got a google mini.

msg.payload.event.team_id

Do you changethe above " team_id" with your teams number?  Example:  msg.payload.event.23  

 Possible to have more than one fav team?

Thanks.

**Comment by dennyreiter** [comment]
It triggers on the goal event coming from Home Assistant NHL-API

**Comment by nutsofamily** [comment]
Ok so what ever teams I have configured, it will play all the horns? i am following 4 teams, so if they are all playing it will trigger them all?

**Comment by dennyreiter** [comment]
Correct.

**Comment by nutsofamily** [comment]
I get Entity could not be found in cache for entity_id: input_boolean.goal_horn
![Screen Shot 2021-03-17 at 4 30 36 PM](https://user-images.githubusercontent.com/24458433/111551772-31e8e200-873e-11eb-902a-865762dd97ab.png)

**Comment by nutsofamily** [comment]
![Screen Shot 2021-03-17 at 4 34 22 PM](https://user-images.githubusercontent.com/24458433/111552016-b50a3800-873e-11eb-8e16-396654024b94.png)

**Comment by dennyreiter** [comment]
Have a look at this for the Amazon audio:
https://community.home-assistant.io/t/play-a-local-mp3-file-on-alexa-echo-dot/186187/23

**Comment by dennyreiter** [comment]
You'll have to create the input_boolean in Home Assistant, under Configuration, then Helpers. Or you can just bypass it if you don't want it.

**Comment by nutsofamily** [comment]
I have it configured like yours as i have the Nabu casa linked to my local files (similar to yours but a different directory).
Doing a quick automation script google mini will play the file correctly, just not from the node-red flow.
I dont know what is wrong because other than the name of media player (mine is living room) and the files i have downloaded and moved to my local file served with Nabu, i get the identity error,

**Comment by nutsofamily** [comment]
Input boolean….. Ugh, more reading. 
I beleive I am just wasting your time. Though for sure by getting the google device and mirroring your config (other than names) it would work.

Sorry for wasting your time.

**Comment by dennyreiter** [comment]
No worries, you are fine.  If you want, you can delete the node that says "Goal Horn Status" and connect the set flow node and delay node directly.

**Comment by nutsofamily** [comment]
Ill give er a go with the montreal game tonight

**Comment by nutsofamily** [comment]
Ok deleting status the test function works. Lets see if it pulls from the Montreal game as I have the Canadiens in my config yaml which I assume it pulls from.




`
  - platform: nhl_api
    name: "NHL Montreal Canadiens"
    team_id: 8`

`      nhl_montreal_canadiens_away_team: 
        entity_picture_template: "{{ states.sensor.nhl_montreal_canadiens.attributes.away_logo }}"
        friendly_name_template: "{{ states.sensor.nhl_montreal_canadiens.attributes.away_name }}"
        value_template: "{{ states.sensor.nhl_montreal_canadiens.attributes.away_score }}"
      nhl_montreal_canadiens_home_team: 
        entity_picture_template: "{{ states.sensor.nhl_montreal_canadiens.attributes.home_logo }}"
        friendly_name_template: "{{ states.sensor.nhl_montreal_canadiens.attributes.home_name }}"
        value_template: "{{ states.sensor.nhl_montreal_canadiens.attributes.home_score }}"`

**Comment by nutsofamily** [comment]
EPIC!!! Montreal scored and I received the horn and light. Thanks!

**Comment by dennyreiter** [comment]
Excellent!

**Comment by dennyreiter** [comment]
If you want to put the goal horn boolean back in, go here:
[![Open your Home Assistant instance and show your helper entities.](https://my.home-assistant.io/badges/helpers.svg)](https://my.home-assistant.io/redirect/helpers/)

Then click "+ Add Helper" in the bottom right corner.  Select Toggle, the top option, then name it "Goal Horn"
